### PR TITLE
Feature/better dynamic dropdown

### PR DESCRIPTION
**Pull request by apaniel90vp**
## Description

There are a couple of features with this PR:

1. a dropdown can now affect the content of another dropdown

1. Multiple dropdowns
the API of the mapper has been updated to be able to generate more than one dropdown depending on the object generated.
image

1. Autocomplete
Dropdowns have now the autocomplete feature to avoid a lot of scrolling for dropdowns with a lot of content
image

### CODE REVIEW

**Review by teleaziz — APPROVED** [review]
👍

**Comment by steve8708** [comment]
@apaniel90vp is this backwards compatible so good to publish?

**Comment by apaniel90vp** [comment]
@steve8708 I might not set that very clear in the MR, but the API of the mapper has a major change, so no, it is not backwards compatible

**Comment by steve8708** [comment]
Thanks @apaniel90vp 

@mrkoreye can you take over getting this released. Let's release it with the tag `v2` so VistaPrint can use the new version via adding `@v2` at the end of the plugin config

**Comment by mrkoreye** [comment]
@apaniel90vp a new version has been published. It is version 2.0.0, and can be accessed using the `@next` tag (or `2.0.0`), i.e. `@builder.io/plugin-dynamic-dropdown@next`. Let me know if updating the plugin config in Builder to include the new version works for you.

**Comment by apaniel90vp** [comment]
awesome @mrkoreye, I'll test asap

**Pull request merged**
