### PR TITLE
possible fix for video autoplay on iOS Safari

### PR DESCRIPTION
**Pull request by steve8708**

### CODE REVIEW

**Review by mrkoreye — APPROVED** [review]

**Review by ca136 — APPROVED** [review]

**Comment by steve8708** [comment]
so I've been testing this and a bunch of other updates on the iOS simulator and none seem to work 😭 

I did notice.... the our current live code works when the (simulator) is in landscape, but not portrait... I have no clue what's going on here

**Comment by mrkoreye** [comment]
maybe iOS sent an update that breaks it? does an old version of our code work?

**Comment by steve8708** [comment]
damn, just confirmed it actually does work on `1.3.21` which is before the removeAttribute update. I'll keep poking

**Comment by steve8708** [comment]
............................................................................................. it was user error

**Pull request closed without merging**
