### PR TITLE
fix duplicates in srcset when width is provided in image input, close…

### PR DESCRIPTION
**Pull request by teleaziz**
…s #117

### CODE REVIEW

**Comment by steve8708** [comment]
This is issuesome since srcset is saying for x size use y url

If we give a default URL but then in the srcset don't still say that x url is the right url for that size, the browser will choose the next largest match

I'm not sure the reasoning for this amp error but removing the default size from the srcset has other issues

I think we need to know more background on the error for the full fix, e.g. is the issue that our width param is a max width and some URL values have the same width even tho they are different?

**Comment by steve8708** [comment]
My have misunderstood this - reopening to continue the discussion

**Comment by steve8708** [comment]
Nvm, apologies for my mistake, I think your approach here may be a fix, did you verify on the amp validator?

**Comment by teleaziz** [comment]
This issue seems to happen only when the width is provided in the src attribute:
```jsx
<img
  decoding="async"
  sizes="(max-width: 638px) 95vw, (max-width: 998px) 97vw,  27vw"
 
 src="https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=966" 
 
 srcset="https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=100 100w,
 https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=200 200w,
 https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=400 400w, 
 https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=800 800w, 
 https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=1200 1200w, 
 https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=1600 1600w, 
 https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=2000 2000w, 
{ src ==> } https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=966, 
 https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=606 606w, 
 
{duplicated here ==> }
https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=966 966w, 
 https://cdn.builder.io/api/v1/image/assets%2F24f5a903f204406989735cec9b19a2ae%2Fa1ad2666656f402c8ad345feedde0e85?width=366 366w"

class="i-amphtml-fill-content i-amphtml-replaced-content">
```

**Pull request merged**
