### PR TITLE
Virto Commerce integration

### PR DESCRIPTION
**Pull request by basilkot**
## Description

Virto Commerce integration. Uses GraphQL for [Virto Commerce](https://virtocommerce.org/).

### CODE REVIEW

**Comment by OlegoO** [comment]
@teleaziz @gustavocodess Any updates with this PR?

**Comment by gustavocodess** [comment]
Hey @OlegoO I'll be reviewing this and give you feedback until tomorrow morning! Great work on this 👍

**Review by gustavocodess — APPROVED** [review]
Looks good

**Comment by gustavocodess** [comment]
@OlegoO please use our .prettier config files from other plugins and run yarn lint fix so I can merge your changes

**Comment by basilkot** [comment]
@gustavocodess I didn't see any .prettier file in the others modules. Can you send a link to an example file?

**Comment by gustavocodess** [comment]
> @gustavocodess I didn't see any .prettier file in the others modules. Can you send a link to an example file?

Actually you should run `yarn lint:fix`, just go to the root of the repo and run the command and you should be good (https://github.com/BuilderIO/builder/blob/main/tslint.json)

**Comment by basilkot** [comment]
@gustavocodess 
done!

**Comment by OlegoO** [comment]
@gustavocodess  @teleaziz  We updated PR. And I seee that it was approved. Are you waiting something from our side?

**Pull request merged**
